version: '3.6'
services:
  comms-services:
    image: comms-service-image
    container_name: comms-service-container
    ports:
    - 7001:7001
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 7001
      TWILIO_ACCOUNT_SID: <VALUE>
      TWILIO_API_KEY: <VALUE>
      TWILIO_API_SECRET: <VALUE>
    restart: always
